### ISSUE TITLE
U key does not launch url from globals file

### ISSUE THREAD

**Issue by saxondigital** [openantz/antz#121]
Status: open
Owner: nobody
Labels: None
Updated: 22 hours ago
Created: 1 day ago
Creator: Jeff Sale
Private: No

I have tried a variety of things to get the U key to work as described. Please explain how this is supposed to work in the latest (June 29) version. I can still hard code my own url and recompile ANTz and I can do what I need to do, but how exactly are the globals files supposed to work?

When I hard code a url that is different from the the url in the globals file antz0001globals.csv and then load antz0001node.csv with the 1 key, the hard-coded url in ANTz overrides the url in the globals file. This seems to be different from the cheat sheet explanation of how it should work.

There are some other things I am unclear about. For example, when I delete all csv files in /usr/csv/ and run my recompiled version of ANTz, it saves two files, antzglobals.csv and antz(null).csv. What is this second one? The url which is saved in the globals file is the url I hard coded in ANTz, which makes sense, but these files do not appear to have any use. 

When I add some objects and hit Shift-1 to save as antz0001node.csv, this works fine. When I re-run ANTz and reload the saved file with shift-1 and select an object and hit the U key, nothing happens except the record_id is displayed in the console. It appears that this is because record_id = 0, since if I edit the csv and set record_id = id then the url is launched. However, this is very confusing and not explained clearly in the cheat sheet. It would be better to launch the url and use id=0 than have nothing happen when record_id = 0. Does this make sense? 

---
Shane Saxon

The globals CSV file allows for setting global parameters upon app startup and whenever loading a dataset. A variety of parameters are contained in the globals table.

There is a default 'antzglobals.csv' that is loaded (or generated if none exists,) upon app startup.

Also, each dataset can (optionally) have its own 'antz....globals.csv' which will be loaded with that dataset.

You should not need to hard-code the default URL anymore. Simply change it in the globals CSV file. Note that if you save with SHIFT+1 then a custom globals file is written, and 'antz0001globals.csv' is the file that is loaded back in when pressing 1.

In regards to launching a browser with id=0 this seems a little odd, since always the same. However, would not be difficult to do. Perhaps we could add a setting for to turn ON/OFF this behavior?

also see:

http://sourceforge.net/p/openantz/wiki/antzglobals.csv/

**Comment by saxondigital** [comment]
Change apps behavior such that only the numeral of the record_id number is appended to the base URL (stored in the globals table.) Currently it appends "…id=" prefix syntax when appending the number, instead allow the prefix syntax to be defined as part of the base URL for greater flexibility.

Base URL examples:
http://github.com/openantz/antz/issues/
http://openantz.com/docs/url.html?id=

**Comment by jsale** [comment]
Timing on this was very good since I am trying to use the U-key database feature for a current project. The latest version does not work. I hit the U key and nothing happens except "record_id = 0" is displayed in the console. I try loading data which loads fine in the most recent versions of ANTz prior to this one but it crashes with this version. Not sure how to attach a csv. I will email you separately with the node and tag files.

**Comment by jsale** [comment]
Test these files with the latest ANTz (Jan. 15).

**Comment by saxondigital** [comment]
Will change the default behavior to open a browser window regardless if record_id = 0.

Also, going to remove the auto-appended syntax '?id=' to the URL.

Appended syntax will now need to be included with the URL (specified in the antzglobals.csv file.) 

Example:
URL = 'https://github.com/openantz/antz/issues/'
Appended record_id formats as '….antz/issues/121'

This allows greater flexibility to be compatible with websites that use different syntax.
