### ISSUE TITLE
Need MySQL support for Links

### ISSUE THREAD

**Issue by jsale** [openantz/antz#139]
I am working on some very interesting and complex node-edge graph data and I could do so much more if mysql supported links. I would say drop everything else and add this feature if it were up to me.

**Comment by jsale** [comment]
Thanks for updating the mysql support for links, but there are a bunch of print statements dumping to the console and severely slowing down the updates. I am working with 50,000 objects, I can't have those print statements. I've tried commenting them out myself and I can get all of them but a dang 23456789 that cycles twice through 50000 updates. We've had issues with print statements dumped to the console slowing things down before. I would hope we can avoid this in the future. Thanks!

**Comment by saxondigital** [comment]
Current mysql_lde branch is being debugged… hence the verbose printf statements. Will cleanup before merge with master. 

Will also look towards a longer term, more general solution for configuring console output for debug vs release purposes.

**Comment by jsale** [comment]
Oh, ok, sorry. It seems to be working ok but I haven't run it fully through
its paces. BTW, it's awesome if I haven't mentioned that lately, fwiw.

**Comment by saxondigital** [comment]
Please do… run it fully through its paces!
New issues #140 #141 #142 #143 

Also, any priority feature requests?
