### ISSUE TITLE
CSV files that exceed kNPnodeChildLimit crash during load

### ISSUE THREAD

**Issue by saxondigital** [openantz/antz#144]
Loading a CSV file that exceeds the kNPnodeChildLimit will crash the app.

kNPnodeChildLimit default is usually set to 64. This restricts graph configurations to a max number of child nodes per parent. Often this is not enough and custom builds are done with an increased limit to satisfy the needs of a specific dataset. But, there is a trade-off as it greatly increases the amount of RAM per node (ie: kNPnodeChildLimit = 256 will add 1KB per node.)

Replacing the fixed size pointer array with a dynamic list would (within RAM limits) solve this problem. This requires a lot work since the array is used extensively throughout the code. Best to probably coordinate this with replacing the home-brewed node data structure with a formal tree library, perhaps a JSON tree based library.

**Comment by jsale** [comment]
Shane,

Technically, the issue that increasing the kNPnodeChildMax "...greatly
increases the amount of RAM per node" is not an issue if we had LOTS of
RAM, right? Well, IMHO people shouldn't be allowed to use ANTz unless they
have LOTS of RAM.   :-)

Forced to choose, I think you should up the default value from 64 to at
least 256, preferrably 1024.

J
