### ISSUE TITLE
Transparency/color_a related crashing

### ISSUE THREAD

**Issue by jsale** [openantz/antz#156]
This seems to occur with all versions I tested including the latest msw 0.198.2. I have been having recent severe crashing issues I have never experienced with ANTz before and which I think I have figured out. I am using transparency (color_a < 255) with ~200,000 objects. ANTz appears to be set to a transparency of subtractive by default, and when I load the data it seems to 'stutter' when it is loading in the console and ultimately hangs. However, if I set the transparency to off before I load the data, it loads smoothly and quickly, all 200,000 objects. I am not sure if this is a performance issue or a bug, but ANTz should probably default to transparency = off. If you can't reproduce this yourself, I can make a sample file available. They are large, of course.

**Comment by saxondigital** [comment]
Jeff, have not seen this issue, even with 2 million nodes.

Can you provide an example file, and specs of the system, including the video card type?\
Also, do you see the problem on multiple systems?

**Comment by saxondigital** [comment]
This is (believed to be) related to a memory bug that is fixed in v0.228.8
