### ISSUE TITLE
Cartesian Coordinate System Topology

### ISSUE THREAD

**Issue by jsale** [openantz/antz#161]
I would like to be able to distribute objects in space in a traditional cartesian coordinate system around a single branch level 0 object. None of the current topologies support this. The basic object geometry in the topology menagerie could be a Grid.

**Comment by saxondigital** [comment]
Grid as a selectable node topo type makes sense, (which is cartesian.)

There has been some thought about allowing a grid to also be a sub-object but all of its children would start at level = 1 (regardless of the level of parent node the grid is attached to.) This would allow combining multiple scenes onto a node tree super-structure.

Or perhaps it makes more sense to re-assign branch-level when doing this type of scene graft… Thoughts?

**Comment by saxondigital** [comment]
Note that the grid topo type has special draw procedures that operate both before and after all other objects are drawn.

**Comment by saxondigital** [comment]
Implemented with 2015-12-01 version.
