### ISSUE TITLE
Skeleton for code

### ISSUE THREAD

**Issue by akowluri** [openantz/antz#162]
My name is Ambarish and I'm interning under Jeff at SDSC and working with ANTz. Is there anyway I can obtain the skeleton for the code or a layout of how the code is organized?

**Comment by saxondigital** [comment]
Currently the best way to see ANTz data structures and function graphs is through Doxygen with GraphViz.

http://openantz.com/docs/doxy/html/

Note that the link above typically lags behind the current code... but is mostly accurate. If you want an up-to-date version you can generate it by installing Doxygen with the Graphviz (DOT) plugin. There is a doxy file located in the 'antz/docs/doxy/' folder.

Info about Doxygen and DOT graphs here:
http://www.stack.nl/~dimitri/doxygen/manual/diagrams.html

**Comment by akowluri** [comment]
Thank you!
