### ISSUE TITLE
VR support for 6DoF interaction

### ISSUE THREAD

**Issue by saxondigital** [openantz/antz#165]
Support 6DoF input devices such as the zSpace stylus.

Current interaction is limited to two dimensions based on mouse emulation.

**Comment by saxondigital** [comment]
ANTz-msw_2019-10-03 (v 0.213.1) adds support for SpaceMouse (aka: SpaceBall, SpaceNavigator, Explorer, etc.) using freeglut version 3.2 (starting in 2014 freeglut 3.0+ has 3Dconnexion support via glutSpaceBall() event callbacks).

Known Bug:
Continual drift occurs if the scope of the current object(s) change while manipulating them.  This is due to the velocity rates (move/rotate/scale) not being reset to zero when another object is selected.

- Important -

TO AVOID strange behavior (like scrollwheel from the spacemouse), config 3Dconnexion settings.

You need to deselect ALL 'Navigation' checkboxes in the 3Dconnexion 'Advanced Settings' preferences.  MAKE SURE that 'antz' app is running an most recent active window (will be displayed within the 3Dconnexion dialog) when changing the settings.  This is because 3Dconnexion settings are NOT global, but instead specific to each app.

<img width="978" alt="ANTz-3Dconnexion-config-b" src="https://user-images.githubusercontent.com/8144433/67287242-95aaa500-f48f-11e9-9266-27b35cab5936.png">

**Comment by saxondigital** [comment]
Add DLL driver detection to avoid (S!.appdll.dll) error dialog on launch for when 3Dconnexion drivers are NOT installed on the system.

**Comment by saxondigital** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Spacemouse (wireless and enterprise versions)](https://trello.com/c/rZd3Ok8v/9-fix-spacemouse-wireless-and-enterprise-versions)

**Comment by saxondigital** [comment]
Support for the newer 3Dconnexion devices has been added with a custom patch to the freeglut.dll and minor changes to the antz core code. Tested with SpaceMouse Wireless and Enterprise editions. Additional info is on the wiki page [3D Mouse](../wiki/3d-mouse).

**Comment by krisrok** [comment]
i was looking for the right place to post this as this is more of a small issue with the wiki, hope it fits in here :)

full disclosure: i'm not a user of your software but another poor dev trying to get spacenav integration right. so your wiki page was a valuable resource, thanks for that!

i have a spacemouse compact and vid and pid match those in your table listing. but my reports are not in the 12/0 format but 6/6. maybe it is just a typo on your page?
