### ISSUE TITLE
OpenAntz MSW 2014-09-13 will not load saved pins for me - bug

### ISSUE THREAD

**Issue by maplesnow** [openantz/antz#168]
A problem is being experienced such that reloading a file containing a root pin and one tag saved using Shift-1 under antz_msw_2014_09_13.does not work.  

The file has one root pin that I created using the N key with a Tag called Test Pin 1.
Saving the file using Shift 1 creates the CSV file.  Examination of the CSV shows the root pin entry.  Exiting the program and then loading the CSV by pressing 1 does not display the root pin.

Using previous versions of OpenAntz (i.e.antz_msw_2014-05-02) I am able to create the root pin, label it, save it using Shift 1, exit the program, run the program and then reload the file by pressing 1.  The pin and tag display fine on the screen.

I have tried to use this version on different computers (Windows 7, Windows 8.1 and most recently Windows 10).and they all experience the same issue.

The 2014-05-02 version works fine on all three operating systems.

Using fsum the following checksum is provided

66d89c5df9a5c0d85ab7620b70d601aa *.DS_Store
d4b778f61206234eea84de62280574d0 *antz.exe
94a031dad72e036bd04761ce4c18be84 *antz_doxy_config
5f41bacff6251f462ede1d2aef74d513 *antz_readme_2014-09-13.txt
5da49269e8b7b84f38ee3d8b88e5a74e *cheatsheet_2014-06-29.txt
a5d5d13813eee5392aadab96b891ac6a *Doxyfile

920148e31827b0cf563b433896f6bd0c *freeglut.dll
ae1f4dacacb463450dde420c0758666d *glut32.dll
0d87daf512930dae58217fb7aa031761 *libmysql.dll
d55c9bec6c7ae3ed7ecb71aef7666f9f *readme.md

**Comment by saxondigital** [comment]
Newer versions have resolved this.

**Comment by maplesnow** [comment]
Thank you.  I will give it a spin.

----- Original Message -----
