### ISSUE TITLE
ANTz GitViz

### ISSUE THREAD

**Issue by lucasviz** [openantz/antz#169]
Uses CURL to pull in issues from the Antz' Github repository.
Uses Jansson to parse CURL results.
To be pushed to the gitviz branch and later pulled into the master.

To use:
- Be connected to the internet.
- Enter the console's command mode.
- type "issues" into the command console and push enter (Double quotes not included).

Viz Details:
Each issue is composed of : 
A pillar 
- Scaled on the Z-Axis depending on how long the issue has existed (before being closed).
- An open issue is colored red, while a closed issue is colored blue.
- Text tagged with the date the issue was opened (and closed, if applicable)

A spheroid
- Texture mapped with the issue assignee's Github avatar.
- Text tagged with the assignee's username.
- If there is no assignee, a spheroid wire-frame is used.

A torus (with an arbitrary number of sub-tori)
- The main torus is text tagged with the issue title.
- Each sub-torus represents an individual label (All Text Tagged).
  - Red, if Bug.
  - Green, if Enhancement.
  - Yellow, if 1st Priority.
  - Unmellow Yellow, if 2nd Priority.

A cube
- Texture mapped with the Github avatar of the user who opened the issue
- Text tagged with their username.

All objects are given the record id corresponding to their issue's number.
If you select any of these objects and push the 'u' key, it will open a browser to the
corresponding Github issue page.

**Comment by saxondigital** [comment]
Be nice to antz-git with interactive selection filters and a few presets.
- Temporal filters.
- Grouped by assignee, priority, etc.
- Attribute mapping to different base graphs, a tree or forest.

**Comment by saxondigital** [comment]
Update tag_id methods to use enhancement issue #197 Add 'tag_id' to node table...
