### ISSUE TITLE
U key still does not open correct url in globals csv

### ISSUE THREAD

**Issue by jsale** [openantz/antz#211]
I just downloaded the latest antz, Dec. 15, and tested the globals file for the sample file antz0001node.csv, i.e. antz0001globals.csv and the url still defaults to openantz.com even when I change it to localhost. When I save a file with the K key and modify that globals file, it still loads the default.

**Comment by saxondigital** [comment]
Looks like adding gitviz repo name (issue #169 ) to the globals.csv broke the 'U' key URL. A similar problem as in earlier this year (issue #121 ).

Thanks for catching this… Will get this fixed ASAP... :)
