### ISSUE TITLE
Labels don't load using the L key for files saved with the K key

### ISSUE THREAD

**Issue by jsale** [openantz/antz#212]
When I save a file using the K key and reload it with the L key the tags/labels do not load. I tested this with the latest antz (Dec. 15, 2015) and sample file antz0001node.csv. The tag file data appears to be saved properly, it just doesn't reload.

**Comment by saxondigital** [comment]
Will look into this… Perhaps something to do with recent changes to the file dialog that allow the user to select images to load, which may effect the identification of file types and/or tag sync.
