### ISSUE TITLE
Select All with ` does not appear to select links.

### ISSUE THREAD

**Issue by jsale** [openantz/antz#214]
When I hit ` to select all objects and then hit the O key to cycle through geometries the link geometries do not change. Likewise for color, transparency, etc.

**Comment by lucasviz** [comment]
This is likely a tree traversal problem, links are special cases.

**Comment by saxondigital** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selection tools](https://trello.com/c/FhHj8nLE/22-selection-tools)
