### ISSUE TITLE
Limitation to number of digits in record_id

### ISSUE THREAD

**Issue by jsale** [openantz/antz#260]
If record_id exceeds 16 digits the format is misinterpreted and returns the wrong value when I hit the U key. I am trying to use the 'id' from a tweet for record_id. An example value would be '965932415679107072', but it is giving me errors even though the value appears to be correct in the csv files.

**Comment by saxondigital** [comment]
Currently ANTz supports record_id using a standard int (32bit). We need to change this to a long int (64bit) to support up to 18 digit id's. This requires modifying the code that reads and writes CSV files as well as the MySQL tables for nodes, tags, etc. Existing CSV files will work without problems. Existing MySQL tables will require some backwards compatibility code to be added.

**Comment by saxondigital** [comment]
Added the file 'stdint.h' which (oddly) is not part of VS2008, for consistent support of 64bit integer type 'int64_t'. Also, typedef of int64 for less typing and improved readability of code.
