### ISSUE TITLE
Commenting print statements improves Channels performance with large files.

### ISSUE THREAD

**Issue by jsale** [openantz/antz#264]
I commented out the following lines in npch.c to significantly speed up performance for channels with large files:

printf("mapping float trackOffset %d to memory address %x\n", trackOffset, attributeValuePtr);

printf("Map trackOffset %d to property %s\n", trackOffset, propertyName);

while (*tokenScanner) printf("token %s\n", *tokenScanner++);

printf("Mapped track offset %d to attribute %s\n", data->io.ch.xref[data->io.ch.xrefIndex].trackOffset,	data->io.ch.xref[data->io.ch.xrefIndex].attributeName);

printf("npChSubscribeNode, list of node property memory address goes from 0x%x to 0%x\n", &ch->ucharTracks.nodePropertyMemoryLocations[0],ch->ucharTracks.nodePropertyMemoryNextLocation);

**Comment by saxondigital** [comment]
Thank you!

Fixed in v0.228.8
