### ISSUE TITLE
File type not supported error when opening saved file

### ISSUE THREAD

**Issue by msroth** [openantz/antz#279]
When I open ANTz, drop a pin, and save the file (using K on keyboard), I cannot reload the file (using L on keyboard).  I get "error 4989 - File type not supported".  This is an unmodified, CSV file that ANTz just saved.  Did I miss something?

**Comment by saxondigital** [comment]
Okay, was able to reproduce  'err 4989' on version *antz-msw-2019-08-25 and plan to fix shortly.  Also noticed that it is not saving thumbnails with the dataset.

*Note that antz-msw-2019-08-25 ( at http://openantz.com/download/msw/ ) is NOT the current git master, but it does have new features and perhaps/hopefully is more stable in general. It does need more testing....

BTW, a workaround is to use SHIFT+1 (2 or 3) to load from the preset names (antz0001...) by renaming your timestamped csv files (antz201909230237node.csv -> antz0001node.csv)

**Comment by saxondigital** [comment]
fixed
