### ISSUE TITLE
Node CSV files do not load properly using the OS command line

### ISSUE THREAD

**Issue by saxondigital** [openantz/antz#298]
Command Line Flags don't work for node CSV tables.

Other file types (tags, images, etc) and command line arguments do seem to work.

**Comment by saxondigital** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Node CSV files do not load properly using the OS command line](https://trello.com/c/HTk3hcAZ/10-node-csv-files-do-not-load-properly-using-the-os-command-line)

**Comment by BradleyGBrandt** [comment]
Here is an interesting observation.

When launching antz with a node file argument that has node objects with a parent id of 0, doesn't render anything and prompts error message: "err 4284 - missing root: 38"

If you launch antz with a node file argument that has node objects with a parent id equal to the id of the main grid, it works just fine.

**Comment by saxondigital** [comment]
Solved by setting 'loadNode' ptr to the root grid in npNodeInit().

Fixed with app v0.234.1

**Comment by saxondigital** [comment]
Appears to be a memory and/or race condition (random timing between file load threads). Also results in the node lock to get stuck (prevents loading or saving any other node files).

**Comment by saxondigital** [comment]
Fixed logic error by removing lockNodes = true from npCmdOpen(). Was redundant to the one in npLoadSyncStart().

Fixed in v1.4.243.22
