### ISSUE TITLE
Add child -> world_x/y/z coordinates to GUI

### ISSUE THREAD

**Issue by anne-Matri** [openantz/antz#305]
User wants to be able to see world x/y/z coords for any child node in the GUI.

**Comment by saxondigital** [comment]
Will do a simple implementation to display nodes->world coordinates in the GUI menu (compass)
-  User can switch GUI from World to Local coordinates by clicking on the the (top menubar item) compass heading.

See wiki for details: [Coordinates](../wiki/Coordinates#gui-compass-indicator)

**Comment by saxondigital** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [enhancement: Universal x, y, z location](https://trello.com/c/bwATd7X5/19-enhancement-universal-x-y-z-location)
