### ISSUE TITLE
Loads scene onto wrong node (as if Alt+L is pressed)

### ISSUE THREAD

**Issue by anne-Matri** [openantz/antz#313]
I used 'L' (not ALT-L), and the new node file loaded onto the object that was selected, vice onto the grid scene.  Unless I use ALT with L, I should be default load a node file onto the primary grid.

**Comment by saxondigital** [comment]
Likely same issue as bug #312 where the Alt key is sticking or a window context change while pressing Alt. However, I would not rule out more obscure possibilities, such as memory corruption of the data structures, etc.

**Comment by saxondigital** [comment]
Fixed in v0.228.8
