### ISSUE TITLE
Textures not found when launching app outside of CWD

### ISSUE THREAD

**Issue by BradleyGBrandt** [openantz/antz#314]
I can only replicate this via Python so far using the following line of code.

os.system(os.path.join(os.sys.path[0], 'antz-xr_2021-06-22_A/') + "ANTz-Xr.exe")

This line will launch antz without Antz being aware of what ever textures are in the usr/images folder

The following line of python can be used as a work around as you can specify the CWD you launch antz from.

subprocess.call(os.sys.path[0] + '/antz-xr_2021-06-22_A/ANTz-Xr.exe', cwd=os.sys.path[0] + '/antz-xr_2021-06-22_A/')

**Comment by saxondigital** [comment]
Fixed with app v0.234.1
