### ISSUE TITLE
Create a `Dockerfile` for running ANTz for Linux on any computer with Docker

### ISSUE THREAD

**Issue by rjurney** [openantz/antz#340]
I am going to make a pass at creating a `Dockerfile` to be able to run Antz on my Intel 64bit Mac.

**Comment by rjurney** [comment]
Oh, I have to update the Linux port first... it has a Dockerfile.

**Comment by jsale** [comment]
Russell, I don't think we've met but if you are ever inclined to update the linux version of ANTz I would be so greatly appreciative. Alas, I don't have the programming skills myself, but I have been part of the HPC community for decades and it has always been frustrating that we could never run ANTz on any of our systems. Just FYI.

**Comment by saxondigital** [comment]
ANTz MSW version is the most up-to-date. Perhaps you can make it run in a Docker container, (I have not tried this).

We use an Intel 64bit Mac with VMware Fusion to run W10 64bit to develop on, (so it definitely works).

Also there is (32bit) ANTz OSX port from 2018 that works up to MacOS Mojave (10.14) here:

https://openantz.com/download/osx/

Lastly, we would like to update the OSX port to 64bit (current OSX requirement) and the (ancient 2014) ANTz Linux port for Ubuntu/RHEL/CentOS.  This does require significant effort/time. Related issues:

- #127
- #126
