### ISSUE TITLE
Rod and Pin offset with orientation

### ISSUE THREAD

**Issue by anne-Matri** [openantz/antz#342]
I'd like to be able to move a child object on a parent object with rod topology on the translate_x axis. 

Right now, the translate_y and translate_z does the same thing as translate_x, just moves the object along the rod. I want to create distance from the rod on the part of the child object.  Is this possible?

Thanks!

**Comment by saxondigital** [comment]
The rod topo is different from a cylinder topo, it is a special case:
- Height of the rod is determined by scale.
- Rod 'scale_x/y/z' does NOT affect child node scale, (unlike most other topos).
- The rods (cylinder) diameter is determined by the 'radius' attribute.
  - Child nodes are positioned at the center of the rod, NOT the surface of rod.
- Child nodes are positioned along the vertical height of the rod based on their 'translate_x' value.

Proposed enhancements:
- A rods child node 'translate_z' would offset the child from the center of rod, (by unscaled units).
- Child node 'translate_y' would orient the (radial) direction of the offset.
  - Note that this differs from a cylinder which uses 'translate_x'.

That is translate_z = 0.0 is the center of the rod, and a positive value would be (radius distance) away from the rod's center axis. The rods 'scale_x/y/z' and 'radius' would have NO affect on the childs 'translate_z' offset.

Note that the default geometry for a rod uses a cylinder and its proportion is based on the 'radius' value (default radius = 0.1, the valid range is 0.01 - 1.0), but you can switch the geometry to anything else.

**Comment by saxondigital** [comment]
Feature added with ANTz ver 233.0

That is 'translate_y' will now set the direction of the radial offset ('translate_z') when the nodes parent 'topo' is either a Rod, RodZ or Pin.

**Comment by saxondigital** [comment]
Update mouse 'Move' and 'Combo' tools to allow modifying the translate Y and Z axes.
  - Perhaps continue to restrict 'translate_y' for 'Combo' tool to prevent accidental re-orientation of tori, etc.

**Comment by saxondigital** [comment]
Implemented in v0.233.4 (2022-12-18).
