### ISSUE TITLE
Textures not displaying properly

### ISSUE THREAD

**Issue by BradleyGBrandt** [openantz/antz#373]
Took a custom screen shot usting windows + shift + s. Saved the result as a png and a jpg. 

When using the textures on the main grid. The png was tiled into a repeating pattern. The jpg was warped to have a diagonal seam. 

When editing the images to have pixels divisible by 4. The jpg worked but not the png. 
![AnneRace](https://github.com/openantz/antz/assets/59422589/e7058c15-44a3-4da1-8c0a-57588aa7ef6a)

**Comment by saxondigital** [comment]
Fixed in v1.5.3.2

Alternate (workaround?) is replacing:
FreeImage_GetColorType(srcBitmap) == FIC_RGB

with:
srcImageBPP == 24

Perhaps there is a bug with FreeImage.
